// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXXmLW5E3TvZWNUb4_DXAvKAEqsU4X-FM',
    appId: '1:528639390524:web:ea4b4cc4853ec470ad2439',
    messagingSenderId: '528639390524',
    projectId: 'cobagit1',
    authDomain: 'cobagit1.firebaseapp.com',
    storageBucket: 'cobagit1.firebasestorage.app',
    measurementId: 'G-G7DBCJF0F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjEmh8SLYGiwtWelU4O9A5-6_g_AknoT0',
    appId: '1:528639390524:android:6e504d2180addd61ad2439',
    messagingSenderId: '528639390524',
    projectId: 'cobagit1',
    storageBucket: 'cobagit1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8hHzN8RO3kmNOL0cXQ-WJ5LqxIkoe51Y',
    appId: '1:528639390524:ios:0aa89b97172147d0ad2439',
    messagingSenderId: '528639390524',
    projectId: 'cobagit1',
    storageBucket: 'cobagit1.firebasestorage.app',
    iosBundleId: 'com.example.flutterCompleteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8hHzN8RO3kmNOL0cXQ-WJ5LqxIkoe51Y',
    appId: '1:528639390524:ios:0aa89b97172147d0ad2439',
    messagingSenderId: '528639390524',
    projectId: 'cobagit1',
    storageBucket: 'cobagit1.firebasestorage.app',
    iosBundleId: 'com.example.flutterCompleteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXXmLW5E3TvZWNUb4_DXAvKAEqsU4X-FM',
    appId: '1:528639390524:web:b09db8b54574a3b6ad2439',
    messagingSenderId: '528639390524',
    projectId: 'cobagit1',
    authDomain: 'cobagit1.firebaseapp.com',
    storageBucket: 'cobagit1.firebasestorage.app',
    measurementId: 'G-6XD7S7TT9F',
  );
}
